### ISSUE TITLE
Extractor can't always properly log users that leave

### ISSUE THREAD

**Issue by chandler05** [Beatso1/extractor#23]
When a user leaves, often the user id will be logged and the user that left will be unknown.

I suggest that instead of logging the user ID in a mention when they leave, instead print the user's tag without a mention.

**Comment by chasecrampton** [comment]
actually a good idea
maybe same with join so it would be like:
**big joe** joined the server. `69420`

**Comment by chandler05** [comment]
I think it's probably fine to leave it for the join unless it is changed for consistency.

**Comment by chasecrampton** [comment]
consistency is key

**Comment by DTRW919** [comment]
Right, might as well save them a ping when joining. Like Chromus said, consistency is key, it'd appear more uniform if so as well.

**Comment by chasecrampton** [comment]
bruh the only thing i care about it consistency lmao

**Comment by DTRW919** [comment]
haha alr

**Comment by chasecrampton** [comment]
wasnt making a joke

**Comment by chandler05** [comment]
Doesn't seem fixed

**Comment by chasecrampton** [comment]
> Doesn't seem fixed

beatso hasn't updated the bot yet

**Comment by chandler05** [comment]
Oh, mb. Didn't realize that it had to be updated manually, sorry about that.

**Comment by chasecrampton** [comment]
np all good
